[package]
name = "rust-restapi-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "8"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
